apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: app
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-service
  template:
    metadata:
      labels:
        app: nginx-service
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: my-service-nginx
  namespace: app
spec:
  selector:
    app: nginx-service
  ports:
  - name: http
    port: 8282
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
